apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-scan-input-nfs-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.221.135
    path: /srv/nfs/scan-input
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scan-input-nfs
  namespace: devsecops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: app-scan-input-nfs-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-clean-output-nfs-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.221.135
    path: /srv/nfs/scan-input-2
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clean-output-nfs
  namespace: devsecops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: app-clean-output-nfs-pv
  storageClassName: ""
